services:
  app:
    build: .
    container_name: cesarscoffeecup_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - cesar_net

  web:
    image: caddy:2
    container_name: cesarscoffeecup_caddy
    restart: unless-stopped
    ports:
      - "127.0.0.1:9002:80"
    volumes:
      - .:/var/www
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - cesar_net

  queue:
    build: .
    container_name: cesarscoffeecup_queue
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    volumes:
      - .:/var/www
    networks:
      - cesar_net

  db:
    image: mysql:8.4
    container_name: cesarscoffeecup_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: cesarscoffeecup
      MYSQL_USER: cesar_user
      MYSQL_PASSWORD: Kakibaum66!!
      MYSQL_ROOT_PASSWORD: Kakibaum66!!
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cesar_net    

networks:
  cesar_net:

volumes:
  caddy_data:
  caddy_config:
  db_data:
