name: Deploy to Devserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy app on devserver

        run: |

          cd ~/deploy/caddy/sites/cesarscoffeecup
          git pull origin develop
          docker compose up -d --build
          composer install --no-dev --optimize-autoloader
